name: Push

on: 
  push:
    branches: ["main"]
  workflow_dispatch:

jobs: 
  build: 
    name: Build
    runs-on: ubuntu-latest
    steps:
      - run: echo "The job was automatically triggered by a ${{ github.event_name }} event."
      
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'zulu'
          cache: gradle
          
      - name: Grant execute permission for gradlew
        run: chmod +x gradlew
        working-directory: .
        
      - name: Build with Gradle
        run: ./gradlew assembleDebug
        working-directory: .
        
      - name: Run ktlintCheck
        run: ./gradlew ktlintCheck
        working-directory: .

      - name: Run detekt
        run: ./gradlew detekt
        working-directory: .

      - name: Run unit tests
        run: ./gradlew test
        working-directory: .

      - name: Start emulator
        uses: ReactiveCircus/android-emulator-runner@v2
        with:
          api-level: 33
          target: google_apis
          arch: x86_64
          profile: Nexus 6
          disable-animations: true
          emulator-boot-timeout: 300
          
      - name: Wait for emulator to start
        run: adb wait-for-device shell 'while [[ -z $(getprop sys.boot_completed) ]]; do sleep 1; done;'

      - name: Run connected tests
        run: ./gradlew connectedCheck
        working-directory: .
      
      - name: Print emulator logs
        run: adb logcat -d
